// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3NKh92i-Q6iNcPd-NtD-a47ju4aDasc',
    appId: '1:614253166245:web:7b38fbd5c4ee2e65c7574c',
    messagingSenderId: '614253166245',
    projectId: 'rafeed-6af8a',
    authDomain: 'rafeed-6af8a.firebaseapp.com',
    storageBucket: 'rafeed-6af8a.appspot.com',
    measurementId: 'G-52CZ2G0C4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWt30s3NTV6QgmxHcmCMF64rYcURQ3UNc',
    appId: '1:614253166245:android:4daaa07ff66e004ec7574c',
    messagingSenderId: '614253166245',
    projectId: 'rafeed-6af8a',
    storageBucket: 'rafeed-6af8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMUjW0SGl5ZHWMB-fc0V2UI3XDm7Fvv6U',
    appId: '1:614253166245:ios:ba85cb91394d3f66c7574c',
    messagingSenderId: '614253166245',
    projectId: 'rafeed-6af8a',
    storageBucket: 'rafeed-6af8a.appspot.com',
    iosBundleId: 'com.example.Rafeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMUjW0SGl5ZHWMB-fc0V2UI3XDm7Fvv6U',
    appId: '1:614253166245:ios:ba85cb91394d3f66c7574c',
    messagingSenderId: '614253166245',
    projectId: 'rafeed-6af8a',
    storageBucket: 'rafeed-6af8a.appspot.com',
    iosBundleId: 'com.example.Rafeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3NKh92i-Q6iNcPd-NtD-a47ju4aDasc',
    appId: '1:614253166245:web:57d589b91120c294c7574c',
    messagingSenderId: '614253166245',
    projectId: 'rafeed-6af8a',
    authDomain: 'rafeed-6af8a.firebaseapp.com',
    storageBucket: 'rafeed-6af8a.appspot.com',
    measurementId: 'G-XFT8Q9XN44',
  );
}
